const AUTH_BASE="https://auth.melcloudhome.com";
const TOKEN_URL=`${AUTH_BASE}/connect/token`;
const API_BASE="https://api.melcloudhome.com/api/v1";
const CLIENT_ID="mobile";

async function getOAuth(env){return await env.DB.prepare("SELECT * FROM oauth_tokens ORDER BY updated_at DESC LIMIT 1").first()}
async function saveOAuth(env,t){const now=Date.now(),expires=t.expires_at||now+Number(t.expires_in||3600)*1000;await env.DB.prepare("DELETE FROM oauth_tokens").run();await env.DB.prepare("INSERT INTO oauth_tokens(id,access_token,refresh_token,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),t.access_token||null,t.refresh_token,expires,now,now).run()}
async function refresh(env,row){if(!row?.refresh_token)throw Error("Aucun refresh_token MELCloud enregistré");const body=new URLSearchParams({grant_type:"refresh_token",client_id:CLIENT_ID,refresh_token:row.refresh_token});const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:body.toString()});if(!r.ok)throw Error(`MELCloud OAuth refresh HTTP ${r.status}`);const t=await r.json();if(!t.refresh_token)t.refresh_token=row.refresh_token;await saveOAuth(env,t);return t.access_token}
async function token(env){const row=await getOAuth(env);if(!row)throw Error("Aucun compte MELCloud OAuth enregistré");if(row.access_token&&Number(row.expires_at)>Date.now()+300000)return row.access_token;return refresh(env,row)}
async function mel(env,path,opt={}){let t=await token(env),r=await fetch(`${API_BASE}/${path.replace(/^\//,"")}`,{...opt,headers:{Accept:"application/json, text/plain, */*",...(opt.headers||{}),Authorization:`Bearer ${t}`}});if(r.status===401){t=await refresh(env,await getOAuth(env));r=await fetch(`${API_BASE}/${path.replace(/^\//,"")}`,{...opt,headers:{Accept:"application/json, text/plain, */*",...(opt.headers||{}),Authorization:`Bearer ${t}`}})}return r}
function setting(c,ks){for(const k of ks)if(c?.[k]!=null)return c[k];for(const n of ["settings","unitSettings"]){for(const x of Array.isArray(c?.[n])?c[n]:[]){if(ks.some(k=>k.toLowerCase()===String(x?.name??x?.Name??"").toLowerCase()))return x?.value??x?.Value??null}}return null}
function on(c){return setting(c,["power","Power"])===true||String(setting(c,["power","Power"])).toLowerCase()==="true"}
function room(c){const n=Number.parseFloat(setting(c,["roomTemperature","RoomTemperature","indoorTemperature","IndoorTemperature"]));return Number.isFinite(n)&&n>0&&n<60?n:20}
function temp(c){const n=Number.parseFloat(setting(c,["setTemperature","SetTemperature","targetTemperature","TargetTemperature","defaultTemperature"]));return Number.isFinite(n)&&n>0&&n<60?n:20}
function mode(c){if(!on(c))return"off";const m=String(setting(c,["operationMode","OperationMode"])||"Automatic").toLowerCase();if(m.includes("cool"))return"cool";if(m.includes("heat"))return"heat";if(m.includes("dry"))return"dry";if(m.includes("fan"))return"fan-only";return"auto"}
function fan(c){const s=String(setting(c,["setFanSpeed","SetFanSpeed","fanSpeed","FanSpeed"])??"").toLowerCase();return s.includes("one")||s==="1"?"One":s.includes("two")||s==="2"?"Two":s.includes("three")||s==="3"?"Three":s.includes("four")||s==="4"?"Four":s.includes("five")||s==="5"?"Five":"Auto"}
function devices(cs){return cs.map(c=>({id:String(c.id??c.ID),type:"action.devices.types.THERMOSTAT",traits:["action.devices.traits.TemperatureSetting","action.devices.traits.FanSpeed"],name:{name:c.givenDisplayName??c.GivenDisplayName??"Climatiseur"},willReportState:false,attributes:{availableThermostatModes:"off,on,heat,cool,dry,fan-only,auto",thermostatTemperatureUnit:"C",supportsFanSpeedPercent:false,commandOnlyFanSpeed:false,availableFanSpeeds:{speeds:["Auto","One","Two","Three","Four","Five"].map((n,i)=>({speed_name:n,speed_values:[{lang:"fr",speed_synonym:[n,i?`Vitesse ${i}`:"Automatique"]},{lang:"en",speed_synonym:[n,i?`Speed ${i}`:"Automatic"]}]})),ordered:true}}}))}
async function fulfillment(req,env){const b=await req.json(),id=b?.requestId,intent=b?.inputs?.[0]?.intent;if(!req.headers.get("authorization"))return new Response("Non autorisé",{status:401});const r=await mel(env,"context");if(!r.ok)return Response.json({error:`MELCloud context HTTP ${r.status}`},{status:502});const cs=(await r.json())?.buildings?.[0]?.airToAirUnits||[];if(intent==="action.devices.SYNC")return Response.json({requestId:id,payload:{agentUserId:"melhome_user",devices:devices(cs)}});if(intent==="action.devices.QUERY"){const d={};for(const c of cs){const x=String(c.id??c.ID);d[x]={online:true,status:"SUCCESS",thermostatMode:mode(c),thermostatTemperatureSetpoint:temp(c),thermostatTemperatureAmbient:room(c),currentFanSpeedSetting:fan(c)}}return Response.json({requestId:id,payload:{devices:d}})}if(intent==="action.devices.EXECUTE"){const out=[];for(const cmd of b?.inputs?.[0]?.payload?.commands||[])for(const dev of cmd.devices||[]){const c=cs.find(x=>String(x.id??x.ID)===String(dev.id));if(!c)continue;const p={power:null,operationMode:null,setFanSpeed:null,setTemperature:null,vaneHorizontalDirection:null,vaneVerticalDirection:null,temperatureIncrementOverride:null,inStandbyMode:null},s={online:true,thermostatMode:mode(c),thermostatTemperatureSetpoint:temp(c),currentFanSpeedSetting:fan(c)};for(const e of cmd.execution||[]){if(e.command==="action.devices.commands.OnOff"){p.power=!!e.params.on;s.thermostatMode=e.params.on?"auto":"off"}if(e.command==="action.devices.commands.ThermostatTemperatureSetpoint"){p.setTemperature=e.params.thermostatTemperatureSetpoint;s.thermostatTemperatureSetpoint=e.params.thermostatTemperatureSetpoint}if(e.command==="action.devices.commands.ThermostatSetMode"){const m=e.params.thermostatMode;s.thermostatMode=m;if(m==="off")p.power=false;else{if(!on(c)&&p.power===null)p.power=true;p.operationMode=({cool:"Cool",heat:"Heat",dry:"Dry","fan-only":"Fan",auto:"Automatic"})[m]??null}}if(e.command==="action.devices.commands.SetFanSpeed"){p.setFanSpeed=e.params.fanSpeed;s.currentFanSpeedSetting=e.params.fanSpeed}}const u=await mel(env,`ataunit/${encodeURIComponent(dev.id)}`,{method:"PUT",headers:{"Content-Type":"application/json; charset=utf-8"},body:JSON.stringify(p)});out.push(u.ok?{ids:[String(dev.id)],status:"SUCCESS",states:s}:{ids:[String(dev.id)],status:"ERROR",errorCode:"hardError"})}return Response.json({requestId:id,payload:{commands:out}})}return Response.json({requestId:id,payload:{}})}
function page(body,status=200){return new Response(`<!doctype html><html lang="fr"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="font-family:system-ui;max-width:700px;margin:40px auto;padding:20px">${body}</body></html>`,{status,headers:{"content-type":"text/html;charset=utf-8"}})}
export default{async fetch(req,env){const u=new URL(req.url);try{if(req.method==="GET"&&u.pathname==="/api/status"){const o=await getOAuth(env);return Response.json({ok:true,oauthSession:!!o?.refresh_token,tokenExpiresAt:o?.expires_at??null})}if(req.method==="POST"&&u.pathname==="/api/save-oauth"){const b=await req.json();if(!b?.refresh_token)return Response.json({error:"refresh_token manquant"},{status:400});await saveOAuth(env,b);return Response.json({success:true})}if(req.method==="GET"&&u.pathname==="/oauth/auth"){const ru=u.searchParams.get("redirect_uri")||"",st=u.searchParams.get("state")||"";if(!ru)return new Response("redirect_uri manquant",{status:400});return page(`<h2>Associer MELHome</h2><form method="POST" action="/oauth/login"><input type="hidden" name="redirect_uri" value="${ru.replace(/"/g,"&quot;")}"><input type="hidden" name="state" value="${st.replace(/"/g,"&quot;")}"><p>La session MELCloud doit être synchronisée depuis l'application Android.</p><button>Continuer</button></form>`)}if(req.method==="POST"&&u.pathname==="/oauth/login"){const f=await req.formData(),ru=String(f.get("redirect_uri")||""),st=String(f.get("state")||""),o=await getOAuth(env);if(!o?.refresh_token)return new Response("Aucune session MELCloud OAuth. Ouvre l'application Android pour synchroniser le compte.",{status:400});const code=`auth_${crypto.randomUUID()}`;await env.DB.prepare("INSERT OR REPLACE INTO oauth_codes(code,created_at) VALUES(?,?)").bind(code,Date.now()).run();const sep=ru.includes("?")?"&":"?";return Response.redirect(`${ru}${sep}code=${encodeURIComponent(code)}&state=${encodeURIComponent(st)}`,302)}if(req.method==="POST"&&u.pathname==="/oauth/token"){const f=await req.formData(),code=String(f.get("code")||""),row=await env.DB.prepare("SELECT * FROM oauth_codes WHERE code=?").bind(code).first();if(!row||Date.now()-Number(row.created_at)>600000)return Response.json({error:"invalid_grant"},{status:400});await env.DB.prepare("DELETE FROM oauth_codes WHERE code=?").bind(code).run();return Response.json({access_token:`melhome-google-${crypto.randomUUID()}`,token_type:"Bearer",expires_in:31536000})}if(req.method==="POST"&&u.pathname==="/fulfillment")return fulfillment(req,env);if(req.method==="GET"&&u.pathname==="/health")return Response.json({status:"ok",service:"melhome-bridge-cloudflare"});if(req.method==="GET"&&u.pathname==="/"){const o=await getOAuth(env);return page(`<h1>❄️ MELHome Bridge</h1><p>Cloudflare opérationnel</p><p>OAuth MELCloud : <b>${o?.refresh_token?"OK":"NON CONFIGURE"}</b></p>`)}return new Response("Not found",{status:404})}catch(e){console.error("[MELHOME]",e);return Response.json({error:e?.message||"Internal error"},{status:500})}}};
